In [25]:
import psycopg2
import pandas as pd

In [26]:
def create_database():
    conn = psycopg2.connect("host = localhost dbname =postgres user=postgres password = Namidok@98")
    conn.set_session(autocommit=True)
    cur = conn.cursor()
    
    ## create sparkify database with UTF8 encoding
    cur.execute("DROP DATABASE IF EXISTS accounts")
    cur.execute("CREATE DATABASE accounts")
    
    ### close connection to default database
    conn.close()
    
    ##connect to sparkify database
    conn = psycopg2.connect("host = localhost dbname =postgres user=postgres password = Namidok@98")
    cur = conn.cursor()
    
    return cur,conn

In [27]:
def drop_tables(cur, conn):
    for query in drop_table_queries:
        cur.execute(query)
        conn.commit()

In [28]:
def create_tables(curr,conn):
    for query in create_table_queries:
        cur.execute(query)
        conn.commit()

In [29]:
#### Read CSV File "Wealth-AccounsCountry.csv" ####

AccountsCountry = pd.read_csv('D:\Wealth-AccountsCountry.csv')

In [30]:
### .head() is to only showcase the top 5 records in the CSV file##

AccountsCountry.head()

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2020 (expected),"Demographic and Health Survey, 2017/18",NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
1,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2020 (expected),"Multiple Indicator Cluster Survey, 2019/20",NaN,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina
2,ARM,Republic of Armenia,Upper middle income,Europe & Central Asia,IBRD,NaN,Armenian dram,2020 (expected),"Demographic and Health Survey, 2015/16",NaN,...,"Integrated household survey (IHS), 2016",Yes,2014,NaN,2018.0,2012.0,AM,AM,Armenia,Armenia
3,AUS,Commonwealth of Australia,High income,East Asia & Pacific,NaN,NaN,Australian dollar,2016,NaN,Fiscal year end: June 30; reporting period for...,...,"Expenditure survey/budget survey (ES/BS), 2010",Yes,2015-2016,2013.0,2018.0,2013.0,AU,AU,Australia,Australia
4,AUT,Republic of Austria,High income,Europe & Central Asia,NaN,Euro area,Euro,2011. Population figures compiled from adminis...,NaN,A simple multiplier is used to convert the nat...,...,"Income survey (IS), 2015",Yes,2010,2014.0,2018.0,2010.0,AT,AT,Austria,Austria

In [31]:
##### Getting only particular columns in the CSV ###

AccountsCountry_clean = AccountsCountry[['Code', 'Long Name', 'Income Group', 'Region', 'Currency Unit']]

AccountsCountry_clean.head()

,Code,Long Name,Income Group,Region,Currency Unit
0,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,Albanian lek
1,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,Argentine peso
2,ARM,Republic of Armenia,Upper middle income,Europe & Central Asia,Armenian dram
3,AUS,Commonwealth of Australia,High income,East Asia & Pacific,Australian dollar
4,AUT,Republic of Austria,High income,Europe & Central Asia,Euro

In [32]:
#### Read CSV File "Wealth-AccountsData.csv" ####

AccountsData = pd.read_csv('D:\Wealth-AccountData.csv')

AccountsData.head()

,Country Name,Country Code,Series Name,Series Code,1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],1999 [YR1999],2000 [YR2000],...,2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,Albania,ALB,Human capital (constant 2018 US$),NW.HCA.TO,4.49E+10,4.34E+10,3.71E+10,3.88E+10,4.22E+10,4.36E+10,...,6.610000e+10,6.810000e+10,6.850000e+10,7.080000e+10,7.160000e+10,7.250000e+10,7.370000e+10,7.57E+10,7.80E+10,8.12E+10
1,Albania,ALB,Human capital per capita (constant 2018 US$),NW.HCA.PC,14072.79,13708.99,11794.1,12399.48,13573.26,14118.13,...,2.258200e+04,2.336286e+04,2.359058e+04,2.439397e+04,2.473162e+04,2.509002e+04,2.559371e+04,26326.26,27160.86,28333.68
2,Albania,ALB,"Human capital per capita, employed female (con...",NW.HCA.FEMP.PC,3468.858,3355.549,2868.997,3013.391,3259.893,3424.007,...,2.825336e+03,2.889150e+03,2.848523e+03,2.930234e+03,2.954273e+03,2.957420e+03,2.987545e+03,3072.504,3178.417,3312.927
3,Albania,ALB,"Human capital per capita, employed male (const...",NW.HCA.MEMP.PC,6507.931,6353.737,5466.692,5901.072,6492.73,6872.019,...,1.525319e+04,1.578992e+04,1.579854e+04,1.647360e+04,1.681013e+04,1.699138e+04,1.730701e+04,17817.1,18445.94,19245.19
4,Albania,ALB,"Human capital per capita, female (constant 201...",NW.HCA.FEMA.PC,4893.006,4737.857,4059.321,4191.445,4536.972,4695.071,...,3.529144e+03,3.613606e+03,3.603694e+03,3.683810e+03,3.696744e+03,3.719608e+03,3.767628e+03,3872.142,3992.188,4161.137

In [33]:
##### Getting only particular columns in the CSV ###

AccountData_clean = AccountsData[['Country Name', 'Country Code', 'Series Code']]

AccountData_clean.head()

  Country Name Country Code     Series Code
0      Albania          ALB       NW.HCA.TO
1      Albania          ALB       NW.HCA.PC
2      Albania          ALB  NW.HCA.FEMP.PC
3      Albania          ALB  NW.HCA.MEMP.PC
4      Albania          ALB  NW.HCA.FEMA.PC

In [34]:
#### Read CSV File "Wealth-AccountSeries.csv" ####

AccountSeries = pd.read_csv('D:\Wealth-AccountSeries.csv')

AccountSeries.head()

,Code,Indicator Name,Long definition,Source,Topic,Unit of measure,Periodicity,Reference period,Statistical concept and methodology,Previous Indicator Code,Previous Indicator Name
0,NW.HCA.TO,Human capital (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
1,NW.HCA.PC,Human capital per capita (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
2,NW.HCA.FEMP.PC,"Human capital per capita, employed female (con...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
3,NW.HCA.MEMP.PC,"Human capital per capita, employed male (const...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN
4,NW.HCA.FEMA.PC,"Human capital per capita, female (constant 201...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital,Constant 2018 US$,Annual,1995-2018,Total wealth is calculated by summing up estim...,NaN,NaN

In [35]:
##### Getting only particular columns in the CSV ###

AccountSeries_clean = AccountSeries[['Code', 'Indicator Name', 'Long definition', 'Source', 'Topic']]

AccountSeries_clean.head()

,Code,Indicator Name,Long definition,Source,Topic
0,NW.HCA.TO,Human capital (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
1,NW.HCA.PC,Human capital per capita (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
2,NW.HCA.FEMP.PC,"Human capital per capita, employed female (con...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
3,NW.HCA.MEMP.PC,"Human capital per capita, employed male (const...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
4,NW.HCA.FEMA.PC,"Human capital per capita, female (constant 201...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital

In [36]:
### Removing a column from the table #####

AccountSeries_clean.columns

Index(['Code', 'Indicator Name', 'Long definition', 'Source', 'Topic'], dtype='object')

In [37]:
AccountSeries_clean.drop(['Topic'], axis=1)

,Code,Indicator Name,Long definition,Source
0,NW.HCA.TO,Human capital (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
1,NW.HCA.PC,Human capital per capita (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
2,NW.HCA.FEMP.PC,"Human capital per capita, employed female (con...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
3,NW.HCA.MEMP.PC,"Human capital per capita, employed male (const...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
4,NW.HCA.FEMA.PC,"Human capital per capita, female (constant 201...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
5,NW.HCA.MALE.PC,"Human capital per capita, male (constant 2018 ...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
6,NW.HCA.FSEM.PC,"Human capital per capita, self-employed female...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
7,NW.HCA.MSEM.PC,"Human capital per capita, self-employed male (...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
8,NW.HCA.FEMP.TO,"Human capital, employed female (constant 2018 ...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
9,NW.HCA.MEMP.TO,"Human capital, employed male (constant 2018 US$)",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
10,NW.HCA.FEMA.TO,"Human capital, female (constant 2018 US$)",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
11,NW.HCA.MALE.TO,"Human capital, male (constant 2018 US$)",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
12,NW.HCA.FSEM.TO,"Human capital, self-employed female (constant ...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
13,NW.HCA.MSEM.TO,"Human capital, self-employed male (constant 20...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...
14,NW.NCA.TO,Natural capital (constant 2018 US$),Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
15,NW.NCA.PC,Natural capital per capita (constant 2018 US$),Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
16,NW.NCA.AGRI.PC,"Natural capital per capita, agricultural land ...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
17,NW.NCA.CROL.PC,"Natural capital per capita, agricultural land:...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
18,NW.NCA.PASL.PC,"Natural capital per capita, agricultural land:...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
19,NW.NCA.FISH.PC,"Natural capital per capita, fisheries (constan...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
20,NW.NCA.FECO.PC,"Natural capital per capita, forests: ecosystem...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
21,NW.NCA.FTIM.PC,"Natural capital per capita, forests: timber (c...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
22,NW.NCA.FOSL.PC,"Natural capital per capita, fossil fuels (cons...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
23,NW.NCA.MANG.PC,"Natural capital per capita, mangroves (constan...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
24,NW.NCA.SSOI.PC,"Natural capital per capita, nonrenewable asset...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
25,NW.NCA.SACO.PC,"Natural capital per capita, nonrenewable asset...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
26,NW.NCA.SAGA.PC,"Natural capital per capita, nonrenewable asset...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
27,NW.NCA.MINR.PC,"Natural capital per capita, nonrenewable asset...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
28,NW.NCA.SAOI.PC,"Natural capital per capita, nonrenewable asset...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
29,NW.NCA.PRAR.PC,"Natural capital per capita, protected areas (c...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
30,NW.NCA.RNEW.PC,"Natural capital per capita, renewable (constan...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
31,NW.NCA.AGRI.TO,"Natural capital, agricultural land (constant 2...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
32,NW.NCA.CROL.TO,"Natural capital, agricultural land: cropland (...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
33,NW.NCA.PASL.TO,"Natural capital, agricultural land: pasturelan...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
34,NW.NCA.FISH.TO,"Natural capital, fisheries (constant 2018 US$)",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
35,NW.NCA.FECO.TO,"Natural capital, forests: ecosystem services (...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
36,NW.NCA.FTIM.TO,"Natural capital, forests: timber (constant 201...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
37,NW.NCA.FOSL.TO,"Natural capital, fossil fuels (constant 2018 US$)",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
38,NW.NCA.MANG.TO,"Natural capital, mangroves (constant 2018 US$)",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
39,NW.NCA.SSOI.TO,"Natural capital, nonrenewable assets (constant...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
40,NW.NCA.SACO.TO,"Natural capital, nonrenewable assets: coal (co...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
41,NW.NCA.SAGA.TO,"Natural capital, nonrenewable assets: gas (con...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
42,NW.NCA.MINR.TO,"Natural capital, nonrenewable assets: minerals...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
43,NW.NCA.SAOI.TO,"Natural capital, nonrenewable assets: oil (con...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
44,NW.NCA.PRAR.TO,"Natural capital, protected areas (constant 201...",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
45,NW.NCA.RNEW.TO,"Natural capital, renewable (constant 2018 US$)",Natural capital includes the valuation of rene...,World Bank. 2021. The Changing Wealth of Natio...
46,NW.NFA.TO,Net foreign assets (constant 2018 US$),Net foreign assets is foreign assets minus for...,World Bank. 2021. The Changing Wealth of Natio...
47,NW.NFA.PC,Net foreign assets per capita (constant 2018 US$),Net foreign assets is foreign assets minus for...,World Bank. 2021. The Changing Wealth of Natio...
48,NW.PCA.TO,Produced capital (constant 2018 US$),Produced capital includes the value of machine...,World Bank. 2021. The Changing Wealth of Natio...
49,NW.PCA.PC,Produced capital per capita (constant 2018 US$),Produced capital includes the value of machine...,World Bank. 2021. The Changing Wealth of Natio...
50,NW.TOW.TO,Total wealth (constant 2018 US$),Total wealth is calculated as the sum of produ...,World Bank. 2021. The Changing Wealth of Natio...
51,NW.TOW.PC,Total wealth per capita (constant 2018 US$),Total wealth is calculated as the sum of produ...,World Bank. 2021. The Changing Wealth of Natio...

In [38]:
AccountSeries_clean.head()

,Code,Indicator Name,Long definition,Source,Topic
0,NW.HCA.TO,Human capital (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
1,NW.HCA.PC,Human capital per capita (constant 2018 US$),Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
2,NW.HCA.FEMP.PC,"Human capital per capita, employed female (con...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
3,NW.HCA.MEMP.PC,"Human capital per capita, employed male (const...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital
4,NW.HCA.FEMA.PC,"Human capital per capita, female (constant 201...",Human capital is computed as the present value...,World Bank. 2021. The Changing Wealth of Natio...,Human capital

In [70]:
cur, conn = create_database()

In [71]:
songplay_table_create = ("""CREATE TABLE IF NOT EXISTS accountscountry(
country_code VARCHAR PRIMARY KEY,
short_name VARCHAR,
table_name VARCHAR,
long_name VARCHAR,
currency_unit VARCHAR)""")

In [72]:
cur.execute(songplay_table_create)
conn.commit()

In [73]:
accounts_data_table_create = ("""CREATE TABLE IF NOT EXISTS accountsdata(
country_name VARCHAR,
country_code VARCHAR,
indicator_name VARCHAR,
indicator_code VARCHAR,
year_1995 numeric,
year_2000 numeric,
year_2005 numeric,
year_2010 numeric,
year_2014 numeric)""")
cur.execute(accounts_data_table_create)
conn.commit()

In [84]:
accountseries_data_table_create = ("""CREATE TABLE IF NOT EXISTS accountseries(
series_code VARCHAR,
topic VARCHAR,
indicator_name VARCHAR,
short_definition VARCHAR)""")
cur.execute(accountseries_data_table_create)
conn.commit()

In [75]:
accounts_country_table_insert = ("""INSERT INTO accountscountry(
country_code,
short_name,
table_name,
long_name,
currency_unit)
VALUES (%s,%s,%s,%s,%s)
ON CONFLICT (country_code) DO NOTHING""")

In [76]:
for i , row in AccountsCountry_clean.iterrows():
    cur.execute(accounts_country_table_insert, list(row))

In [77]:
conn.commit()

In [85]:
accountseries_table_insert = ("""INSERT INTO accountseries(
series_code ,
topic,
indicator_name,
short_definition)
VALUES (%s,%s,%s,%s)
""")

In [88]:
for i , row in AccountSeries_clean.iterrows():
    cur.execute(accountseries_table_insert, list(row))

TypeError: not all arguments converted during string formatting

In [ ]:
conn.commit()